// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkA12lOxZ1P0OBg4QOzc_XskqsFLzMYno',
    appId: '1:801102295535:web:95e2d8a344ae0903a1c61a',
    messagingSenderId: '801102295535',
    projectId: 'devil-e3c45',
    authDomain: 'devil-e3c45.firebaseapp.com',
    databaseURL: 'https://devil-e3c45-default-rtdb.firebaseio.com',
    storageBucket: 'devil-e3c45.firebasestorage.app',
    measurementId: 'G-QGDEKEPBP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn075IWGl5KXiMYvPcYawJ1mnITCrh688',
    appId: '1:801102295535:android:fd2b6c4aa68fe879a1c61a',
    messagingSenderId: '801102295535',
    projectId: 'devil-e3c45',
    databaseURL: 'https://devil-e3c45-default-rtdb.firebaseio.com',
    storageBucket: 'devil-e3c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgh5P6aQE18CkmeNjZ8eE33tela4b3sBM',
    appId: '1:801102295535:ios:0e7c182baf9f745ea1c61a',
    messagingSenderId: '801102295535',
    projectId: 'devil-e3c45',
    databaseURL: 'https://devil-e3c45-default-rtdb.firebaseio.com',
    storageBucket: 'devil-e3c45.firebasestorage.app',
    iosBundleId: 'com.example.gymFitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgh5P6aQE18CkmeNjZ8eE33tela4b3sBM',
    appId: '1:801102295535:ios:0e7c182baf9f745ea1c61a',
    messagingSenderId: '801102295535',
    projectId: 'devil-e3c45',
    databaseURL: 'https://devil-e3c45-default-rtdb.firebaseio.com',
    storageBucket: 'devil-e3c45.firebasestorage.app',
    iosBundleId: 'com.example.gymFitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkA12lOxZ1P0OBg4QOzc_XskqsFLzMYno',
    appId: '1:801102295535:web:c837edaf8ea582b5a1c61a',
    messagingSenderId: '801102295535',
    projectId: 'devil-e3c45',
    authDomain: 'devil-e3c45.firebaseapp.com',
    databaseURL: 'https://devil-e3c45-default-rtdb.firebaseio.com',
    storageBucket: 'devil-e3c45.firebasestorage.app',
    measurementId: 'G-L87P71EKMW',
  );
}
